name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BACKEND_IMAGE: backend
  FRONTEND_IMAGE: frontend
  LATEST_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build backend image
      run: |
        docker build -t ${{ env.BACKEND_IMAGE }}:${{ env.LATEST_TAG }} ./NecrosisApi
        docker tag ${{ env.BACKEND_IMAGE }}:${{ env.LATEST_TAG }} ghcr.io/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}:${{ env.LATEST_TAG }}

    - name: Build frontend image
      run: |
        docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.LATEST_TAG }} ./necrosisapp
        docker tag ${{ env.FRONTEND_IMAGE }}:${{ env.LATEST_TAG }} ghcr.io/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE }}:${{ env.LATEST_TAG }}

    - name: Push images to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}:${{ env.LATEST_TAG }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE }}:${{ env.LATEST_TAG }}
