name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build backend image
      run: docker build -t backend:latest ./NecrosisApi

    - name: Build frontend image
      run: docker build -t frontend:latest ./necrosisapp

    # Optionally, add steps to push to Docker Hub or GHCR
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #
    # - name: Push backend image
    #   run: docker tag backend:latest yourdockerhub/backend:latest && docker push yourdockerhub/backend:latest
    #
    # - name: Push frontend image
    #   run: docker tag frontend:latest yourdockerhub/frontend:latest && docker push yourdockerhub/frontend:latest